language: node_js
node_js:
  - 17
cache:
  directories:
  - node_modules
script:
  - npm run lint
  - npm run build
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: out
  fqdn: juliaroedesign.com 
  on:
    branch: master